services:
  database:
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    image: postgres
    container_name: rentx_database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    env_file: .env
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - .:/usr/src/app/node_modules
    links:
      - database
    depends_on: 
      - database
volumes:
  pgdata:
    driver: local