services:
  database:
    build: .
    env_file: _database.env
    image: postgres
    container_name: rentx_database
    restart: always
    network_mode: host
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    env_file: _app.env
    container_name: rentx
    network_mode: host
    volumes:
      - .:/usr/app
      - .:/usr/src/app/node_modules
volumes:
  pgdata:
    driver: local